name: CI/CD Tienda Perritos EKS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Descargar Código
      uses: actions/checkout@v3

    - name: 2. Credenciales AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: 3. Login a Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: 4. Build & Push a ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        TAG: eks-v1 
      run: |
        docker build -t $ECR_REGISTRY/tienda-frontend:$TAG ./frontend
        docker push $ECR_REGISTRY/tienda-frontend:$TAG
        
        docker build -t $ECR_REGISTRY/tienda-backend:$TAG ./backend
        docker push $ECR_REGISTRY/tienda-backend:$TAG
        
        docker build -t $ECR_REGISTRY/tienda-db:$TAG ./db
        docker push $ECR_REGISTRY/tienda-db:$TAG

    - name: 5. Conectar al Clúster EKS
      run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

    - name: 6. Desplegar Infraestructura (Corregido)
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/
        kubectl rollout restart deployment/tienda-db -n tienda
        kubectl rollout restart deployment/tienda-backend -n tienda
        kubectl rollout restart deployment/tienda-frontend -n tienda